### ISSUE TITLE
Beta pages displaying error

### ISSUE THREAD

**Issue by palomao** [PRX/www.prx.org#339]
Newer pieces being published are displaying an error message on the beta site. Older pieces do not seem to be effected.  

Ex: https://beta.prx.org/stories/197177

<img width="766" alt="screen shot 2017-02-06 at 3 04 32 pm" src="https://cloud.githubusercontent.com/assets/17989422/22665990/f1d0d00e-ec84-11e6-8eae-955e3694d532.png">

**Comment by kookster** [comment]
I can get to that page fine, is that https://beta.prx.org/stories/197177 giving you issues @palomao ?

**Comment by palomao** [comment]
Yes, yesterday it was giving me the error message pasted above. It seems to be happening with recently published pieces. I checked the last four pieces published to PRX.org and got the same error message for all the pieces.

https://beta.prx.org/stories/197324
https://beta.prx.org/stories/197327
https://beta.prx.org/stories/197328
https://beta.prx.org/stories/197329

**Comment by cavis** [comment]
Looks to be a CMS issue.  Story exists and should be published/visible, but seeing this in the logs:

```
HalApi::Errors::NotFound (Resource Not Found):
  app/controllers/concerns/child_resource.rb:19:in `show_resource'
```

**Comment by kookster** [comment]
yeah, I saw this too, seems to be an issue in that visibility code, looking
into it more.

**Comment by kookster** [comment]
it's the Story.publish scope.
If it compares against `now()` in the db, it isn't working, but if I pass in Time.now from ruby, it does.

**Comment by kookster** [comment]
ah, fun. 
```
irb(main):028:0> result = Story.connection.exec_query('select now() from dual').rows.first
=> [2017-02-07 13:37:19 UTC]
irb(main):029:0> Time.now.utc
=> 2017-02-07 19:37:24 UTC
```

**Comment by kookster** [comment]
fixed by PRX/cms.prx.org/#248

**Comment by palomao** [comment]
Looks like the problem is still persistent. These two pieces were published today and are still displaying an error message.

https://beta.prx.org/stories/197441
https://beta.prx.org/stories/197469

**Comment by kookster** [comment]
fix wasn't deployed, should be now - pls retry
